routes/web.php
<?php

use App\Models\Person;
use Illuminate\Support\Facades\Route;
use App\Models\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth', 'cookies'])->group(function () {
    Route::get('/', function () {
        return view('dashboard');
    })->name('home');

    Route::resource('users', App\Http\Controllers\UserController::class);
    Route::resource('clubs', App\Http\Controllers\ClubController::class);
    Route::resource('people', App\Http\Controllers\PersonController::class);
    Route::resource('abilities', App\Http\Controllers\AbilityController::class);

});

require __DIR__.'/auth.php';

app/Models/Ability.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Ability extends Model
{
    use SoftDeletes;

    public $timestamps = false;

    protected $guarded = ['id'];

    public function people()
    {
        return $this->belongsToMany(
            Person::class,
            'ability_club_person',
        )->withPivot('id', 'active', 'starting_date', 'ending_date');
    }

    public function clubs()
    {
        return $this->belongsToMany(
            Club::class,
            'ability_club_person',
        )->withPivot('id', 'active', 'starting_date', 'ending_date');
    }
}

app/Http/Controllers/API/AbilityController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Ability;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use Yajra\DataTables\Facades\DataTables;

class AbilityController extends Controller
{
    public function index(Request $request)
    {
        $query = Ability::select([
            'abilities.*',
            DB::raw('COUNT(`ability_club_person`.`person_id`) as `people`'),
            DB::raw('COUNT(`ability_club_person`.`club_id`) as `clubs`'),
        ])->leftJoin('ability_club_person', 'abilities.id', '=', 'ability_club_person.ability_id');

        $query->groupBy('id');

        if ($request->query->has('trashed')) {
            $query = $query->withTrashed();
        }


        return Datatables::of($query)
            ->addColumn('url', fn ($row) => route('abilities.show', $row->id, false))
            ->addColumn('trashed', fn ($row) => $row->trashed())
            ->rawColumns(['url'])
            ->rawColumns(['trashed'])
            ->toJson();
    }

    public function show(Ability $ability)
    {
        $query = DB::table('ability_club_person')
            ->leftJoin('clubs', 'ability_club_person.club_id', 'clubs.id')
            ->leftJoin('people', 'ability_club_person.person_id', 'people.id')
            ->select('ability_club_person.*', 'clubs.name as club', 'people.last_name as person')
            ->where('ability_club_person.ability_id', '=', $ability->id);

        return Datatables::of($query)
            ->editColumn('starting_date', function ($row) {
                return $row->starting_date == '' ? '' :
                    Carbon::createFromFormat('Y-m-d', $row->starting_date)->format('d/m/Y');
            })
            ->editColumn('ending_date', function ($row) {
                return $row->ending_date == '' ? '' :
                    Carbon::createFromFormat('Y-m-d', $row->ending_date)->format('d/m/Y');
            })
            ->editColumn('active', fn ($row) => $row->active == 0 ? false : true)
            ->toJson();
    }
}

app/Http/Controllers/AbilityController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ability;
use App\Models\Club;
use Carbon\Carbon;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\View\View;
use Yajra\DataTables\Facades\DataTables;

class AbilityController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Ability::class);
    }

    public function index(Request $request): View|JsonResponse
    {
        return view('abilities.index')
            ->with('trashed', $request->query->has('trashed'));
    }

    public function show(Ability $ability, Request $request): View|JsonResponse
    {
        $clubs = Club::select(['id', 'name'])->orderBy('name')->get();

        return view('abilities.show')
            ->with([
                'ability' => $ability,
                'clubs' => $clubs,
            ]);
    }

    public function edit(Ability $ability)
    {
        return view('abilities.edit')
            ->with('ability', $ability);
    }

    public function destroy(Ability $ability)
    {
        $ability->delete();

        return redirect(route('abilities.index'))
            ->with('warning', 'Η ιδιότητα έχει διαγραφεί.');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/abilities/edit.blade.php
<x-app-layout>
    <x-slot name="title">{{ $ability->name }}</x-slot>

    <x-slot name="header">
        Ιδιότητα: {{ $ability->name }}
    </x-slot>

    <div class="row row-cols-2 g-2">
    </div>

    <x-slot name="toolbar">
        <div class="d-flex align-items-stretch justify-content-between">
            <div class="btn-group">
                <x-tool href="{{ route('abilities.show', $ability) }}"
                    icon="fas fa-angle-left" />
            </div>
        </div>
    </x-slot>
</x-app-layout>

resources/views/abilities/index.blade.php
<x-app-layout>
    <x-slot name="title">Ιδιότητες</x-slot>

    <x-slot name="header">Κατάλογος ιδιοτήτων</x-slot>

    <div class="card">
        <table class="dataTable table table-hover table-responsive px-0 d-none">
            <thead>
                <tr>
                    <th>Ονομασία</th>
                    <th>Επαφές</th>
                    <th>Σωματεία</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>

    <x-slot name="extra_scripts">
        <script>window.ajaxroute = '/api/abilities{{ $trashed ? '?trashed' : '' }}';</script>
        <script src="{{ mix('js/components/datatables.js') }}" defer></script>
        <script src="{{ mix('js/helpers/abilities.index.js') }}" defer></script>
    </x-slot>

    <x-slot name="toolbar">
        <div class="d-flex align-items-stretch justify-content-between">
            <x-tool href="{{ route('abilities.index') }}{{ $trashed ? '' : '?trashed' }}"
                icon="{{ $trashed ? 'far fa-trash-alt' : false }}"
                type="{{ $trashed ? 'btn-warning' : false }}">
                {{ $trashed ? 'όλες' : 'ενεργές' }}
            </x-tool>
            <x-tool href="{{ route('abilities.create') }}"
                icon="far fa-file"
                type="btn-primary">
                προσθήκη
            </x-tool>
        </div>
    </x-slot>
</x-app-layout>

resources/views/abilities/show.blade.php
<x-app-layout>
    <x-slot name="title">{{ $ability->name }}</x-slot>

    <x-slot name="header">
        Ιδιότητα: <strong>{{ $ability->name }}</strong>
    </x-slot>

    <div class="card">
        <div class="d-none" id="acp_errors">
            <div class="text-danger">
                Ουπς! Κάτι πήγε στραβά!
            </div>

            <ul class="text-danger" id="acp_data">
            </ul>
        </div>
        <h4 class="bg-cyan text-light rounded-top p-3">
            <span id="ability_id" class="d-none">{{ $ability->id }}</span>
            {{ $ability->name }}
        </h4>
        <div class="card-body">
            <h5>Εισαγωγή ιδιότητας</h5>
            <div class="row align-items-center gx-1">
                <div class="col col-sm-2">
                    <div class="autoComplete_wrapper">
                        <x-input
                            name="person"
                            type="text"
                            label="Επαφή"
                            class="acp_field"
                            />
                        <input type="hidden" id="person-id" name="person-id" value="" disabled>

                    </div>
                </div>
                <div class="col col-sm-2">
                    <div class="autoComplete_wrapper">
                        <x-input
                            name="club"
                            type="text"
                            label="Σωματείο"
                            class="acp_field"
                            />
                        <input type="hidden" id="club-id" name="club-id" value="" disabled>
                    </div>
                </div>
                <div class="col col-sm-3">
                    <x-input
                    name="description"
                    type="text"
                    label="Τίτλος"
                    class="acp_field"
                    />
                </div>
                <div class="col col-sm-2">
                    <x-input
                    name="starting_date"
                    type="text"
                    label="Έναρξη"
                    class="acp_field"
                    />
                </div>
                <div class="col col-sm-2">
                    <x-input
                    name="ending_date"
                    type="text"
                    label="Λήξη"
                    class="acp_field"
                    />
                </div>
                <div class="col col-sm-1 text-center pb-3">
                    <x-button id="addRecord" class="btn-primary">Οκ</x-button>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <table class="dataTable table table-hover table-responsive px-0 d-none">
            <thead>
                <tr>
                    <th>Επαφή</th>
                    <th>Σωματείο</th>
                    <th>Τίτλος</th>
                    <th>(Έναρξη)</th>
                    <th>(Λήξη)</th>
                    <th>(Ενεργή)</th>
                    <th><i class="far fa-trash-alt"></i></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>

    <x-slot name="extra_scripts">
        <script>window.ajaxroute1 = '/api/abilities/{{ $ability->id }}';</script>
        <script>window.ajaxroute2 = '/api/ability-club-person';</script>
        <script src="{{ mix('js/components/datatables.js') }}" defer></script>
        <script src="{{ mix('js/helpers/abilities.show.js') }}" defer></script>
    </x-slot>

    <x-slot name="toolbar">
        <div class="d-flex align-items-stretch justify-content-between">
            <div class="btn-group">
                <x-tool href="{{ route('abilities.index') }}"
                    icon="fas fa-angle-left" />
                <x-tool href="{{ route('abilities.edit', ['ability' => $ability]) }}"
                    icon="fas fa-pen"
                    type="btn-primary">
                    αλλαγή
                </x-tool>
            </div>
            <div class="btn-group">
                <form method="POST" action="{{ route('abilities.destroy', ['ability' => $ability]) }}">
                    @csrf
                    {{ method_field('DELETE') }}
                    <x-tool
                        icon="fas fa-trash"
                        type="btn-danger">
                        διαγραφή
                    </x-tool>
                </form>
            </div>
        </div>
    </x-slot>
</x-app-layout>