routes/web.php
<?php

use App\Models\Person;
use Illuminate\Support\Facades\Route;
use App\Models\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth', 'cookies'])->group(function () {
    Route::get('/', function () {
        return view('dashboard');
    })->name('home');

    Route::resource('users', App\Http\Controllers\UserController::class);
    Route::resource('clubs', App\Http\Controllers\ClubController::class);
    Route::resource('people', App\Http\Controllers\PersonController::class);
    Route::resource('abilities', App\Http\Controllers\AbilityController::class);

});

require __DIR__.'/auth.php';

app/Models/Club.php
<?php

namespace App\Models;

use App\Models\Person;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

class Club extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = ['id'];

    protected $casts = [
        'active' => 'boolean',
        'normal_member' => 'boolean',
        'in_athens' => 'boolean',
        'in_major_city' => 'boolean',
        'gga_recognized' => 'boolean',
        'founded' => 'date:d/m/Y',
        'subscription_date' => 'date:d/m/Y',
        'membership_date' => 'date:d/m/Y',
    ];

    public static function boot()
    {
        parent::boot();

        self::creating(function (Club $club) {
            $club->slug = self::get_unique_slug($club);
        });

        self::updating(function (Club $club) {
            $club->slug = self::get_unique_slug($club);
        });
    }

    public function getRouteKeyName(): string
    {
        return 'slug';
    }

    public function manager()
    {
        return $this->belongsTo(Person::class);
    }

    public function addresses()
    {
        return $this->morphMany(Address::class, 'addressable');
    }

    public function athletes()
    {
        return $this->hasMany(Athlete::class);
    }

    public function abilities()
    {
        return $this->belongsToMany(
            Ability::class,
            'ability_club_person',
        )->withPivot('id', 'active', 'starting_date', 'ending_date');
    }

    public function setFoundedAttribute(?string $value)
    {
        $this->attributes['founded'] = getDBDateFromInput($value);
    }

    public function setSubscriptionDateAttribute(?string $value)
    {
        $this->attributes['subscription_date'] = getDBDateFromInput($value);
    }

    public function setMembershipDateAttribute(?string $value)
    {
        $this->attributes['membership_date'] = getDBDateFromInput($value);
    }

    public function headquarters()
    {
        return $this->addresses
            ->where('main', true)
            ->first();
    }

    public function nonHeadquarters()
    {
        return $this->addresses->filter(function ($item) {
            return $item->main == false;
        });
    }

    private static function get_unique_slug(Club $club): string
    {
        $slug = (string) Str::of($club->name)->slug();
        $existing = Club::where('id', '<>', $club->id)
            ->select('slug')->get()->pluck('slug');

        $counter = 1;

        while ($slug === '' || $existing->search($slug) !== false) {
            $slug = 'none-' . $counter;
            $counter++;
        }

        return $slug;
    }
}

app/Models/Person.php
<?php

namespace App\Models;

use App\Models\Club;
use App\Traits\SelfReferenceTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Person extends Model
{
    use HasFactory, SelfReferenceTrait, SoftDeletes;

    protected $guarded = ['id'];

    protected $attributes = [
        'male' => true,
    ];

    protected $casts = [
        'birth_date' => 'date:d/m/Y',
    ];

    public function asset()
    {
        return $this->hasOne(Club::class, 'manager_id');
    }

    public function address()
    {
        return $this->morphOne(Address::class, 'addressable');
    }

    public function athlete()
    {
        return $this->hasOne(Athlete::class);
    }

    public function abilities()
    {
        return $this->belongsToMany(
            Ability::class,
            'ability_club_person',
        )->withPivot('id', 'active', 'starting_date', 'ending_date');
    }

    public function getFullNameAttribute(): string
    {
        return "{$this->last_name} {$this->first_name}";
    }

    public function getImageURLAttribute(): string
    {
        if (is_null($this->id)) {
            return '';
        }

        $filename = 'person/' . image_directory_chunk($this->id) . '/' . $this->id . '.webp';
        if (Storage::exists('public/' . $filename)) {
            return Storage::url('public/' . $filename);
        }

        if ($this->male) {
            return asset('images/male.svg');
        }

        return asset('images/female.svg');
    }

    public function getImageFilenameAttribute(): string
    {
        if (is_null($this->id)) {
            return '';
        }

        return 'public/person/' . image_directory_chunk($this->id) . '/' . $this->id . '.webp';
    }

    public function getAgeAttribute(): string
    {
        return $this->birth_date ? $this->birth_date->age : '';
    }

    public function getPhoneAttribute(?string $value): ?string
    {
        return $this->format_phone_number($value);
    }

    public function setPhoneAttribute(?string $value)
    {
        $this->attributes['phone'] = $this->strip_spaces($value);
    }

    public function getMobileAttribute(?string $value): ?string
    {
        return $this->format_phone_number($value);
    }

    public function setMobileAttribute(?string $value)
    {
        $this->attributes['mobile'] = $this->strip_spaces($value);
    }

    public function setBirthDateAttribute(?string $value)
    {
        $this->attributes['birth_date'] = getDBDateFromInput($value);
    }

    private function strip_spaces(?string $value): ?string
    {
        if ($value) {
            $value = preg_replace("/[^\d]/", "", $value);
        }
        return $value;
    }

    private function format_phone_number(?string $value): ?string
    {
        if ($value && strlen($value) == 10) {
            $value = preg_replace("/^1?(\d{3})(\d{3})(\d{4})$/", "$1 $2 $3", $value);
        }
        return $value;
    }
}

app/Http/Controllers/ClubController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ClubPostRequest;
use App\Jobs\ClubCreatedOrChanged;
use App\Models\Club;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class ClubController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Club::class);
    }

    public function index(Request $request): View
    {
        $clubs = Club::orderBy('name');

        if ($request->query->has('trashed')) {
            $clubs = $clubs->withTrashed();
        }

        return view('clubs.index')
            ->with('clubs', $clubs->get())
            ->with('trashed', $request->query->has('trashed'));
    }

    public function create() : View
    {
        return view('clubs.edit')
            ->with('club', Club::make());
    }

    public function store(ClubPostRequest $request): RedirectResponse
    {
        DB::beginTransaction();

        $club = Club::create($this->get_merged_club_data($request));

        if (!$this->save_club_addresses($club, $request)) {
            DB::rollBack();
            abort(500, 'Πρόβλημα με την αποθήκευση διευθύνσεων.');
        }

        DB::commit();

        ClubCreatedOrChanged::dispatch($club);

        return redirect(route('clubs.show', ['club' => $club]))
            ->with('info', 'Τα στοιχεία του σωματείου αποθηκεύτηκαν.');
    }

    public function show(Club $club): View
    {
        $club->load('addresses', 'manager');

        return view('clubs.show')
            ->with('club', $club);
    }

    public function edit(Club $club): View
    {
        $club->load('addresses', 'manager');

        return view('clubs.edit')
            ->with('club', $club);
    }

    public function update(ClubPostRequest $request, Club $club): RedirectResponse
    {
        $old_email = $club->email;

        DB::beginTransaction();

        $club->update($this->get_merged_club_data($request));

        if (!$this->save_club_addresses($club, $request)) {
            DB::rollBack();
            abort(500, 'Πρόβλημα με την αποθήκευση διευθύνσεων.');
        }

        DB::commit();

        if ($old_email != $club->email) {
            ClubCreatedOrChanged::dispatch($club);
        }

        return redirect(route('clubs.show', ['club' => $club]))
            ->with('info', 'Τα στοιχεία του σωματείου αποθηκεύτηκαν.');
    }

    public function destroy(Club $club): RedirectResponse
    {
        $club->delete();

        return redirect(route('clubs.index'))
            ->with('warning', 'Το σωματείο έχει διαγραφεί.');
    }

    private function get_merged_club_data(ClubPostRequest $request): array
    {
        return array_merge(
            $request->validated(),
            [
                'active' => $request->has('active') && in_array($request->active, ['1', 'on']),
                'normal_member' => $request->has('normal_member') && in_array($request->normal_member, ['1', 'on']),
                'in_athens' => $request->has('in_athens') && in_array($request->in_athens, ['1', 'on']),
                'in_major_city' => $request->has('in_major_city') && in_array($request->in_major_city, ['1', 'on']),
                'gga_recognized' => $request->has('gga_recognized') && in_array($request->gga_recognized, ['1', 'on']),
            ]
        );
    }

    private function save_club_addresses(Club $club, ClubPostRequest $request): bool
    {
        if ($request->has('address_id')) {
            for ($w = 0; $w < count($request->address_id); $w++) {
                $address_data = [
                    'main' => $request->address_main === 'row-' . $w ? true : false,
                    'street' => $request->address_street[$w],
                    'region' => $request->address_region[$w],
                    'zip' => $request->address_zip[$w],
                    'city' => $request->address_city[$w],
                    'country' => $request->address_country[$w],
                    'phone' => $request->address_phone[$w],
                ];

                if ($request->address_id[$w] === 'new') {
                    if ($request->address_deleted[$w] === 'false') {
                        // new address non deleted
                        if (!$club->addresses()->create($address_data)) {
                            return false;
                        }
                    }
                } else {
                    $address = $club->addresses->find($request->address_id[$w]);
                    if (is_null($address)) {
                        Log::channel('single')->error('Could not find Address.', [
                            'controller' => (new \ReflectionClass(get_called_class()))->getShortName(),
                            'address_id' => $request->address_id[$w],
                            'club_id' => $club->id,
                        ]);
                        return false;
                    }

                    if ($request->address_deleted[$w] === 'false') {
                        // existing address non deleted
                        if (!$address->update($address_data)) {
                            Log::channel('single')->error('Could not update Address.', [
                                'controller', (new \ReflectionClass(get_called_class()))->getShortName(),
                                'address_id', $address->id,
                                'club_id', $club->id,
                            ]);
                            return false;
                        }
                    } else {
                        if (!$address->delete()) {
                            Log::channel('single')->error('Could not delete Address.', [
                                'controller', (new \ReflectionClass(get_called_class()))->getShortName(),
                                'address_id', $address->id,
                                'club_id', $club->id,
                            ]);
                            return false;
                        }
                    }
                }
            }
        }

        return true;
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/clubs/index.blade.php
<x-app-layout>
    <x-slot name="title">Σωματεία</x-slot>

    <x-slot name="header">Κατάλογος σωματείων</x-slot>

    <div class="card">
        <table class="table table-hover table-striped my-0 d-none">
            <thead>
                <tr>
                    <th>Όνομα</th>
                    <th>Email</th>
                    <th>Ενεργό</th>
                    <th>Πλήρες μέλος</th>
                    <th>Αθηναϊκό</th>
                    <th>Αθ/Θεσ</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($clubs as $club)
                <tr data-url="{{ route('clubs.show', ['club' => $club]) }}" class="clicky pointy{{ $club->trashed() ? ' bg-warning' : '' }}">
                    <td{!! $club->trashed() ? ' class="text-decoration-line-through"' : '' !!}>{{ $club->name }}</td>
                    <td{!! $club->trashed() ? ' class="text-decoration-line-through"' : '' !!}>{{ $club->email }}</td>
                    <td><x-check-icon value="{{ $club->active }}" /></td>
                    <td><x-check-icon value="{{ $club->normal_member }}" /></td>
                    <td><x-check-icon value="{{ $club->in_athens }}" /></td>
                    <td><x-check-icon value="{{ $club->in_major_city }}" /></td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <x-slot name="toolbar">
        <div class="d-flex align-items-stretch justify-content-between">
            <x-tool href="{{ route('clubs.index') }}{{ $trashed ? '' : '?trashed' }}"
                icon="{{ $trashed ? 'far fa-trash-alt' : false }}"
                type="{{ $trashed ? 'btn-warning' : false }}">
                {{ $trashed ? 'όλα' : 'ενεργά' }}
            </x-tool>
            <x-tool href="{{ route('clubs.create') }}"
                icon="far fa-file"
                type="btn-primary">
                προσθήκη
            </x-tool>
        </div>
    </x-slot>

    <x-slot name="extra_scripts">
        <script src="{{ mix('js/components/datatables.js') }}" defer></script>
        <script src="{{ mix('js/helpers/clubs.index.js') }}" defer></script>
    </x-slot>

</x-app-layout>

resources/views/clubs/show.blade.php
<x-app-layout>
    <x-slot name="title">{{ $club->name }}</x-slot>

    <x-slot name="header">
        Καρτέλα: {{ $club->name }}
    </x-slot>

    <div class="row row-cols-2 g-2">
        <!-- Γενικά Στοιχεία -->
        <div class="col">
            <div class="card">
                <h4 class="bg-cyan text-light rounded-top p-3">Γενικά στοιχεία</h4>
                <div class="card-body">
                    <div class="card-text">
                        <div class="row">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Όνομα</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $club->full_name }}</div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Email</h6>
                            </div>
                            <div class="col-9 text-secondary">
                                <a href="mailto:{{ $club->name }}<{{ $club->email }}>" target="_blank">{{ $club->email }}</a>
                                <i class="text-sm fas fa-external-link-alt text-gray-400"></i>
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Ιστοχώρος</h6>
                            </div>
                            <div class="col-9 text-secondary align-baseline">
                                <a href="{{ $club->website }}" target="_blank">{{ $club->website }}</a>
                                @if($club->website)<i class="text-sm fas fa-external-link-alt text-gray-400"></i>@endif
                            </div>
                        </div>
                        <hr />
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Ενεργό</h6>
                            </div>
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Πλήρες μέλος</h6>
                            </div>
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Αθηναϊκό</h6>
                            </div>
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Αθ/Θεσ</h6>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-3">
                                <x-check-icon value="{{ $club->active }}" />
                            </div>
                            <div class="col-3">
                                <x-check-icon value="{{ $club->normal_member }}" />
                            </div>
                            <div class="col-3">
                                <x-check-icon value="{{ $club->in_athens }}" />
                            </div>
                            <div class="col-3">
                                <x-check-icon value="{{ $club->in_major_city }}" />
                            </div>
                        </div>
                        <hr />
                    </div>
                </div>
            </div>
        </div>

        <!-- Επικοινωνία -->
        <div class="col">
            <div class="card">
                <h4 class="bg-gray-300 text-secondary rounded-top p-3">Επικοινωνία</h4>
                <div class="card-body">
                    <div class="card-text">
                        <!-- Υπεύθυνος -->
                        @if ($club->manager)
                        <div class="row mb-4">
                            <div class="col-1 text-center">
                                <span class="align-bottom d-block"><i class="fas fa-user text-cyan"></i></span>
                                <span class="align-bottom d-block mt-2"><i class="fas fa-phone"></i></span>
                                <span class="align-bottom d-block mt-2"><i class="fas fa-mobile"></i></span>
                                <span class="align-bottom d-block mt-2"><i class="fas fa-envelope"></i></span>
                        </div>
                            <div class="col-11">
                                <span class="align-bottom d-block"><a href="{{ route('people.show', $club->manager) }}">{{ $club->manager->full_name }}</a>&nbsp;</span>
                                <span class="align-bottom d-block mt-2"><a href="tel:{{ $club->manager->phone }}">{{ $club->manager->phone }}</a>&nbsp;</span>
                                <span class="align-bottom d-block mt-2"><a href="tel:{{ $club->manager->mobile }}">{{ $club->manager->mobile }}</a>&nbsp;</span>
                                <span class="align-bottom d-block mt-2">
                                    <a href="mailto:{{ $club->manager->full_name }}<{{ $club->manager->email }}>" target="_blank">{{ $club->manager->email }}</a>
                                    @if($club->manager->email)<i class="text-sm fas fa-external-link-alt text-gray-400"></i>@endif
                                </span>
                            </div>
                        </div>
                        @endif
                        <!-- Διευθύνσεις -->
                        @if ($club->headquarters())
                        <div class="row mb-4">
                            <div class="col-1 text-center">
                                <i class="fas fa-map-marker text-cyan"></i>
                            </div>
                            <div class="col-11">
                                {!! nl2br($club->headquarters()->toMultiline()) !!}
                            </div>
                        </div>
                        @endif
                        @foreach ($club->nonHeadquarters() as $item)
                        <div class="row mb-4">
                            <div class="col-1 text-center">
                                <i class="fas fa-map-marker"></i>
                            </div>
                            <div class="col-11">
                                {!! nl2br($item->toMultiline()) !!}
                            </div>
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row row-cols-2 g-2 row mb-4">
        <!-- EOM -->
        <div class="col">
            <div class="card">
                <h4 class="bg-gray-300 text-secondary rounded-top p-3">Στοιχεία ΕΟΜ</h4>
                <div class="card-body">
                    <div class="card-text">
                        <div class="row">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Ίδρυση</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $club->founded ? $club->founded->format('d/m/Y') : '' }}</div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Καταστατικό</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $club->bylaws }}</div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Εγγραφή</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $club->subscription_date ? $club->subscription_date->format('d/m/Y') : '' }}</div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Πρωτόκολλο</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $club->subscription_protocol }}</div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Μέλος</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $club->membership_date ? $club->membership_date->format('d/m/Y') : '' }}</div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Πρωτόκολλο</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $club->membership_protocol }}</div>
                        </div>
                        <hr />
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <!-- Εφορία -->
            <div class="card">
                <h4 class="bg-gray-300 text-secondary rounded-top p-3">Στοιχεία Εφορίας</h4>
                <div class="card-body">
                    <div class="card-text">
                        <div class="row">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">ΑΦΜ</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $club->irs_vat_number }}</div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Στοιχεία Εφορίας</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $club->irs_location }}</div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Έδρα</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $club->irs_headquarters }}</div>
                        </div>
                        <hr />
                    </div>
                </div>
            </div>

            <!-- ΓΓΑ -->
            <div class="card mb-0">
                <h4 class="bg-gray-300 text-secondary rounded-top p-3">Στοιχεία ΓΓΑ</h4>
                <div class="card-body">
                    <div class="card-text">
                        <div class="row">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Κωδικός</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $club->gga_code }}</div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Πρωτόκολλο</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $club->gga_protocol }}</div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Αναγνωρισμένο</h6>
                            </div>
                            <div class="col-9 text-secondary"><x-check-icon value="{{ $club->gga_recognized }}" /></div>
                        </div>
                        <hr />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <x-slot name="toolbar">
        <div class="d-flex align-items-stretch justify-content-between">
            <div class="btn-group">
                <x-tool href="{{ route('clubs.index') }}"
                    icon="fas fa-angle-left" />
                <x-tool href="{{ route('clubs.edit', ['club' => $club]) }}"
                    icon="fas fa-pen"
                    type="btn-primary">
                    αλλαγή
                </x-tool>
            </div>
            <div class="btn-group">
                <form method="POST" action="{{ route('clubs.destroy', ['club' => $club]) }}">
                    @csrf
                    {{ method_field('DELETE') }}
                    <x-tool
                        icon="fas fa-trash"
                        type="btn-danger">
                        διαγραφή
                    </x-tool>
                </form>
            </div>
        </div>
    </x-slot>
</x-app-layout>