routes/web.php
<?php

use App\Models\Person;
use Illuminate\Support\Facades\Route;
use App\Models\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth', 'cookies'])->group(function () {
    Route::get('/', function () {
        return view('dashboard');
    })->name('home');

    Route::resource('users', App\Http\Controllers\UserController::class);
    Route::resource('clubs', App\Http\Controllers\ClubController::class);
    Route::resource('people', App\Http\Controllers\PersonController::class);
    Route::resource('abilities', App\Http\Controllers\AbilityController::class);

});

require __DIR__.'/auth.php';

app/Models/Person.php
<?php

namespace App\Models;

use App\Models\Club;
use App\Traits\SelfReferenceTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Person extends Model
{
    use HasFactory, SelfReferenceTrait, SoftDeletes;

    protected $guarded = ['id'];

    protected $attributes = [
        'male' => true,
    ];

    protected $casts = [
        'birth_date' => 'date:d/m/Y',
    ];

    public function asset()
    {
        return $this->hasOne(Club::class, 'manager_id');
    }

    public function address()
    {
        return $this->morphOne(Address::class, 'addressable');
    }

    public function athlete()
    {
        return $this->hasOne(Athlete::class);
    }

    public function abilities()
    {
        return $this->belongsToMany(
            Ability::class,
            'ability_club_person',
        )->withPivot('id', 'active', 'starting_date', 'ending_date');
    }

    public function getFullNameAttribute(): string
    {
        return "{$this->last_name} {$this->first_name}";
    }

    public function getImageURLAttribute(): string
    {
        if (is_null($this->id)) {
            return '';
        }

        $filename = 'person/' . image_directory_chunk($this->id) . '/' . $this->id . '.webp';
        if (Storage::exists('public/' . $filename)) {
            return Storage::url('public/' . $filename);
        }

        if ($this->male) {
            return asset('images/male.svg');
        }

        return asset('images/female.svg');
    }

    public function getImageFilenameAttribute(): string
    {
        if (is_null($this->id)) {
            return '';
        }

        return 'public/person/' . image_directory_chunk($this->id) . '/' . $this->id . '.webp';
    }

    public function getAgeAttribute(): string
    {
        return $this->birth_date ? $this->birth_date->age : '';
    }

    public function getPhoneAttribute(?string $value): ?string
    {
        return $this->format_phone_number($value);
    }

    public function setPhoneAttribute(?string $value)
    {
        $this->attributes['phone'] = $this->strip_spaces($value);
    }

    public function getMobileAttribute(?string $value): ?string
    {
        return $this->format_phone_number($value);
    }

    public function setMobileAttribute(?string $value)
    {
        $this->attributes['mobile'] = $this->strip_spaces($value);
    }

    public function setBirthDateAttribute(?string $value)
    {
        $this->attributes['birth_date'] = getDBDateFromInput($value);
    }

    private function strip_spaces(?string $value): ?string
    {
        if ($value) {
            $value = preg_replace("/[^\d]/", "", $value);
        }
        return $value;
    }

    private function format_phone_number(?string $value): ?string
    {
        if ($value && strlen($value) == 10) {
            $value = preg_replace("/^1?(\d{3})(\d{3})(\d{4})$/", "$1 $2 $3", $value);
        }
        return $value;
    }
}

app/Http/Controllers/API/PersonController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Models\Person;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class PersonController extends Controller
{
    public function index(Request $request)
    {
        $query = Person::select([
            'people.*',
            'clubs.name as clubname',
        ])->leftJoin('clubs', 'people.id', '=', 'clubs.manager_id');

        if ($request->query->has('trashed')) {
            $query = $query->withTrashed();
        }

        return Datatables::of($query)
            ->addColumn('url', function($row) {
                return route('people.show', $row->id, false);
            })
            ->addColumn('trashed', function($row) {
                return $row->trashed();
            })
            ->rawColumns(['url'])
            ->rawColumns(['trashed'])
            ->toJson();
    }
}

app/Http/Controllers/PersonController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PersonPostRequest;
use App\Models\Person;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\View;
use Intervention\Image\Facades\Image;

class PersonController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Person::class);
    }

    public function index(Request $request): View|JsonResponse
    {
        return view('people.index')
            ->with('trashed', $request->query->has('trashed'));
    }

    public function show(Person $person): View
    {
        return view('people.show')->with('person', $person);
    }

    public function create()
    {
        return view('people.edit')
            ->with('person', Person::make());
    }

    public function store(PersonPostRequest $request)//: RedirectResponse
    {

        $person = Person::create($this->get_merged_person_data($request));

        if ($request->image) {
            $this->savePersonImage($request->image, $person->imageFilename);
        }

        return redirect(route('people.show', ['person' => $person]))
            ->with('info', 'Τα στοιχεία της επαφής ενημερώθηκαν.');
    }

    public function edit(Person $person): View
    {
        return view('people.edit')
            ->with('person', $person);
    }

    public function update(PersonPostRequest $request, Person $person): RedirectResponse
    {
        $person->update($this->get_merged_person_data($request));

        if ($request->image || $request->image_delete) {
            Storage::delete($person->imageFilename);
        }

        if ($request->image) {
            $this->savePersonImage($request->image, $person->imageFilename);
        }

        return redirect(route('people.show', ['person' => $person]))
            ->with('info', 'Τα στοιχεία της επαφής ενημερώθηκαν.');
    }

    public function destroy(Person $person) : RedirectResponse
    {
        $person->delete();

        return redirect(route('people.index'))
            ->with('warning', 'Η επαφή έχει διαγραφεί.');
    }

    private function savePersonImage(UploadedFile $image, string $filename)
    {
        $path = dirname($filename);
        if (!Storage::exists($path)) {
            Storage::makeDirectory($path);
        }

        Image::make($image)
            ->fit('500', '500')
            ->encode('webp', 90)
            ->save(Storage::path($filename));
    }

    private function get_merged_person_data(PersonPostRequest $request): array
    {
        return array_merge(
            $request->validated(),
            [
                'male' => $request->has('male') && in_array($request->male, ['1', 'on']),
            ]
        );
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/people/edit.blade.php
<x-app-layout>
    <x-slot name="title">{{ $person->id ? 'Επεξεργασία επαφής ' . $person->last_name : 'Νέα επαφή' }}</x-slot>

    <x-slot name="header">
        {{ $person->id ? 'Επεξεργασία επαφής ' . $person->last_name : 'Νέα επαφή' }}
    </x-slot>

    <!-- Validation Errors -->
    <x-auth-validation-errors class="mb-4" :errors="$errors" />

    <!-- form -->
    <form method="POST" enctype=multipart/form-data action="{{ $person->id ? route('people.update', ['person' => $person ]) : route('people.store') }}">
        @csrf
        {{ $person->id ? method_field('PUT') : '' }}
        <div class="row row-cols-1 g-2 mb-4 d-print-none">
            <!-- Γενικά Στοιχεία -->
            <div class="col-md-12">
                <div class="card">
                    <h4 class="bg-cyan text-light rounded-top p-3">Γενικά στοιχεία</h4>
                    <div class="card-body">
                        <div class="card-text">
                            <!-- Όνομα -->
                            <x-input
                                name="first_name"
                                type="text"
                                label="Όνομα"
                                value="{{ old('first_name') ?: $person->first_name }}"
                                autofocus
                            />
                            <!-- Επώνυμο -->
                            <x-input
                                name="last_name"
                                type="text"
                                required
                                label="Επώνυμο"
                                value="{{ old('last_name') ?: $person->last_name }}"
                            />
                            <!-- Αρχικό -->
                            <x-input
                                name="initial"
                                type="text"
                                label="Αρχικό"
                                value="{{ old('initial') ?: $person->initial }}"
                            />
                            <!-- Φύλλο -->
                            <x-input-radio-sex
                                name="male"
                                value="{{ old('active') ?: $person->male }}"
                            />
                            <!-- Γέννηση -->
                            <x-input
                                name="birth_date"
                                type="text"
                                label="Γέννηση"
                                value="{{ old('birth_date') ?: ($person->birth_date ? $person->birth_date->format('d/m/Y') : '') }}"
                            />
                            <!-- Τηλέφωνο -->
                            <x-input
                                name="phone"
                                type="text"
                                label="Τηλέφωνο"
                                value="{{ old('phone') ?: $person->phone }}"
                            />
                            <!-- Κινητό -->
                            <x-input
                                name="mobile"
                                type="text"
                                label="Κινητό"
                                value="{{ old('mobile') ?: $person->mobile }}"
                            />
                            <!-- Email -->
                            <x-input
                                name="email"
                                type="email"
                                label="Email"
                                value="{{ old('email') ?: $person->email }}"
                            />
                            <!-- Πατρώνυμο -->
                            <x-input
                                name="fathers_name"
                                type="text"
                                label="Πατρώνυμο"
                                value="{{ old('fathers_name') ?: $person->fathers_name }}"
                            />
                            <!-- Επάγγελμα -->
                            <x-input
                                name="profession"
                                type="text"
                                label="Επάγγελμα"
                                value="{{ old('profession') ?: $person->profession }}"
                            />
                            <!-- Ταυτότητα -->
                            <x-input
                                name="identity_card"
                                type="text"
                                label="Αρ. Ταυτ."
                                value="{{ old('identity_card') ?: $person->identity_card }}"
                            />
                            <!-- Φωτογραφία -->
                            <x-input-image
                                name="image"
                                label="Εικόνα"
                                value="{{ $person->imageURL }}"
                            />
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="d-print-none d-flex align-items-stretch justify-content-between">
            <x-button class="btn-primary">{{ $person->id ? 'Ενημέρωση' : 'Αποθήκευση' }}</x-button>
        </div>
    </form>

    <x-slot name="toolbar">
        <div class="btn-group">
            <x-tool href="{{ $person->id ? route('people.show', ['person' => $person]) : route('people.index') }}"
                icon="fas fa-angle-left" />
        </div>
    </x-slot>
</x-app-layout>

resources/views/people/index.blade.php
<x-app-layout>
    <x-slot name="title">Επαφές</x-slot>

    <x-slot name="header">Κατάλογος επαφών</x-slot>

    <div class="card">
        <table class="dataTable table table-hover table-responsive px-0 d-none">
            <thead>
                <tr>
                    <th>Επώνυμο</th>
                    <th>Όνομα</th>
                    <th>Email</th>
                    <th>Τηλέφωνο</th>
                    <th>Κινητό</th>
                    <th>Υπεύθυνος</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>

    <x-slot name="toolbar">
        <div class="d-flex align-items-stretch justify-content-between">
            <x-tool href="{{ route('people.index') }}{{ $trashed ? '' : '?trashed' }}"
                icon="{{ $trashed ? 'far fa-trash-alt' : false }}"
                type="{{ $trashed ? 'btn-warning' : false }}">
                {{ $trashed ? 'όλες' : 'ενεργές' }}
            </x-tool>
            <x-tool href="{{ route('people.create') }}"
                icon="far fa-file"
                type="btn-primary">
                προσθήκη
            </x-tool>
        </div>
    </x-slot>

    <x-slot name="extra_scripts">
        <script>window.ajaxroute = '/api/people{{ $trashed ? '?trashed' : '' }}';</script>
        <script src="{{ mix('js/components/datatables.js') }}" defer></script>
        <script src="{{ mix('js/helpers/people.index.js') }}" defer></script>
    </x-slot>
</x-app-layout>

resources/views/people/show.blade.php
<x-app-layout>
    <x-slot name="title">{{ $person->last_name }}</x-slot>

    <x-slot name="header">
        Καρτέλα: {{ $person->last_name }}
    </x-slot>

    <div class="row row-cols-2 g-2">
        <!-- Γενικά Στοιχεία -->
        <div class="col col-content">
            <div class="card col-content">
                <h4 class="bg-cyan text-light rounded-top p-3">Γενικά στοιχεία</h4>
                <div class="card-body">
                    <div class="card-text">
                        <div class="row mb-4 text-center">
                            <div class="col-12">
                                <img src="{{ $person->imageURL }}" class="img-fluid rounded-circle mb-1" width="128" height="128" />
                            </div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Όνομα</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $person->first_name }}</div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Επώνυμο</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $person->last_name }}</div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Αρχικό</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $person->initial }}</div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Φύλλο/Ηλικία</h6>
                            </div>
                            <div class="col-9 text-secondary">
                                {{ $person->male ? 'άνδρας' : 'γυναίκα' }}
                                {{ $person->age ? $person->age . ' ετών' : '' }}
                            </div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Τηλέφωνο</h6>
                            </div>
                            <div class="col-9 text-secondary"><a href="tel:{{ $person->phone }}">{{ $person->phone }}</a></div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Κινητό</h6>
                            </div>
                            <div class="col-9 text-secondary"><a href="tel:{{ $person->mobile }}">{{ $person->mobile }}</a></div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Email</h6>
                            </div>
                            <div class="col-9 text-secondary">
                                <a href="mailto:{{ $person->full_name }}<{{ $person->email }}>" target="_blank">{{ $person->email }}</a>
                                @if($person->email)<i class="text-sm fas fa-external-link-alt text-gray-400"></i>@endif

                            </div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Πατρώνυμο</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $person->fathers_name }}</div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Επάγγελμα</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $person->profession }}</div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Αρ. Ταυτ.</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $person->identity_card }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Dummy -->
        <div class="col col-content">
            <div class="card col-content">
                <h4 class="bg-gray-300 text-secondary rounded-top p-3">Σημειώσεις</h4>
                <div class="card-body">
                    <div class="card-text">

                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="row row-cols-2 g-2 row mb-4">
        <!-- Αθλητικά στοιχεία -->
        <div class="col">
            <div class="card flex">
                <div
                    class="{{ $person->athlete ? 'bg-cyan text-white' : 'bg-gray-300 text-secondary' }} rounded-top p-3 d-flex justify-content-between"
                    data-bs-toggle="collapse"
                    href="#collapseAthleticData"
                    role="button"
                >
                    <h4>Αθλητικά Στοιχεία</h4>
                    <i class="fas fa-chevron-down"></i>
                </div>
                <div class="card-body collapse" id="collapseAthleticData">
                    <div class="card-text">
                    @if($person->athlete)
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Μητρώο</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ codeFormat($person->athlete->code) }}</div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Σωματείο</h6>
                            </div>
                            <div class="col-9 text-secondary">
                            @if ($person->athlete->club)
                                <a href="{{ route('clubs.show', $person->athlete->club) }}">{{ $person->athlete->club->name }}</a>
                            @endif
                            </div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Εγγραφή</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ $person->athlete->subscription ? $person->athlete->subscription->format('d/m/Y') : '' }}</div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Ανανέωση</h6>
                            </div>
                            <div class="col-9 text-secondary">
                            @if($person->athlete->update)
                                {{ $person->athlete->update->format('d/m/Y') }}
                                {!! $person->athlete->updateColor !!}
                            @endif
                            </div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Κατηγορία</h6>
                            </div>
                            <div class="col-9 text-secondary">
                            @if ($person->athlete->category)
                                {{ $person->athlete->category }}
                                - {{ categoryName($person->athlete->category) }}
                            @endif
                            </div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Μαύροι</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ numberFormat($person->athlete->black) }}</div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Χρυσοί</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ numberFormat($person->athlete->gold) }}</div>
                        </div>
                        <div class="row mb-4">
                            <div class="col-3">
                                <h6 class="mb-0 text-muted">Πλατινένιοι</h6>
                            </div>
                            <div class="col-9 text-secondary">{{ numberFormat($person->athlete->platinum, 1) }}</div>
                        </div>
                    @endif
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <!-- Dummy -->
            <div class="card flex">
                <div
                    class="bg-gray-300 text-secondary rounded-top p-3 d-flex justify-content-between"
                    data-bs-toggle="collapse"
                    href="#collapseDummy"
                    role="button"
                >
                    <h4>Dummy</h4>
                    {{-- <x-icon.chevron-down /> --}}
                </div>
                <div class="card-body collapse" id="collapseDummy">
                    <div class="card-text">

                    </div>
                </div>
            </div>

        </div>

    </div>

    <x-slot name="toolbar">
        <div class="d-flex align-items-stretch justify-content-between">
            <div class="btn-group">
                <x-tool href="{{ route('people.index') }}"
                    icon="fas fa-angle-left" />
                <x-tool href="{{ route('people.edit', ['person' => $person]) }}"
                    icon="fas fa-pen"
                    type="btn-primary">
                    αλλαγή
                </x-tool>
            </div>
            <div class="btn-group">
                <form method="POST" action="{{ route('people.destroy', ['person' => $person]) }}">
                    @csrf
                    {{ method_field('DELETE') }}
                    <x-tool
                        icon="fas fa-trash"
                        type="btn-danger">
                        διαγραφή
                    </x-tool>
                </form>
            </div>
        </div>
    </x-slot>
</x-app-layout>