routes/web.php
<?php

use App\Models\Person;
use Illuminate\Support\Facades\Route;
use App\Models\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth', 'cookies'])->group(function () {
    Route::get('/', function () {
        return view('dashboard');
    })->name('home');

    Route::resource('users', App\Http\Controllers\UserController::class);
    Route::resource('clubs', App\Http\Controllers\ClubController::class);
    Route::resource('people', App\Http\Controllers\PersonController::class);
    Route::resource('abilities', App\Http\Controllers\AbilityController::class);

});

require __DIR__.'/auth.php';

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="author" content="Takis Pournaras">
    <link rel="shortcut icon" href="/logo.svg">

    <title>{{ isset($title) ? $title . ' | ' : '' }}GREET</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.googleapis.com">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap">

    <!-- Styles -->
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">

    <!-- Scripts -->
    <script src="{{ mix('js/app.js') }}" defer></script>
    @isset($extra_scripts){{ $extra_scripts }}@endisset

</head>
<body>
    <div class="wrapper">
        <!-- Navigation -->
        @include('layouts.sidebar')

        <!-- Main -->
        <div class="main">
            @include('layouts.header')

            @include('layouts.toolbar')

            <!-- Page Content -->
            <main class="content">
                <div class="container-fluid p-0">
                    {{ $slot }}
                </div>
            </main>

            <!-- Page Footer -->
            @include('layouts.footer')
        </div>
    </div>
    @include('flash-messages')
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="footer d-print-none">
    <div class="container-fluid">
        <div class="row row-cols-2 text-muted">
            <div class="col text-start">
                <p class="mb-0 text-muted">
                    Ελληνική Ομοσπονδία Μπριτζ © 2021
                </p>
            </div>
            {{-- <div class="col text-end">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a class="p-0 m-0 btn disabled" href="#" tabindex="-1" role="button" aria-disabled="true">Υποστήριξη</a>
                    </li>
                </ul>
            </div> --}}
        </div>
    </div>
</footer>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="author" content="Takis Pournaras">
    <link rel="shortcut icon" href="/logo.svg">

    <title>{{ isset($title) ? $title . ' | ' : '' }}GREET</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.googleapis.com">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap">

    <!-- Styles -->
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">

    <!-- Scripts -->
    <script src="{{ mix('js/app.js') }}" defer></script>
</head>
<body>
    <div class="d-flex w-100">
        <div class="container d-flex flex-column">
            <div class="row vh-100">
                <div class="col-sm-10 col-md-8 col-lg-6 mx-auto d-table h-100">
                    <div class="d-table-cell align-middle">
                        {{ $slot }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

resources/views/layouts/header.blade.php
<!-- Main Nav -->
<nav class="navbar navbar-expand navbar-light navbar-bg">
    <a class="d-print-none sidebar-toggle js-sidebar-toggle">
        <i class="hamburger align-self-center"></i>
    </a>
    @isset($header)
        <!-- Header -->
        <h3 class="font-semibold text-gray-800 leading-tight mb-0 pb-0">
            {{ $header }}
        </h3>
    @endisset

    <div class="navbar-collapse collapse">
        <div class="d-none d-print-flex navbar-nav navbar-align sidebar-brand">
            <x-application-logo
                class="logo-small p-0 m-0 align-middle d-inline-block"
                text="REET" />
        </div>
        <ul class="d-print-none navbar-nav navbar-align">
            <li class="nav-item dropdown">
                <a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-bs-toggle="dropdown">
                    <i class="fas fa-align-left"></i>
                </a>

                <a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-bs-toggle="dropdown">
                    <span class="text-dark">{{ Auth::user()->name }}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-end">
                    <!-- Settings -->
                    <a class="dropdown-item" href="{{ route('users.show', ['user' => Auth::user()]) }}">
                        <i class="fas fa-user"></i>
                        <span class="align-middle">Προφίλ</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <!-- Authentication -->
                    <form method="POST" action="{{ route('logout') }}">
                        @csrf

                        <a class="dropdown-item" href="route('logout')"
                            onclick="event.preventDefault();
                            this.closest('form').submit();">
                            Αποσύνδεση
                        </a>
                    </form>
                </div>
            </li>
        </ul>
    </div>
</nav>

resources/views/layouts/sidebar.blade.php
<nav id="sidebar" class="d-print-none sidebar js-sidebar {{ $cookies['sidebar'] ?? '' }}">
    <div class="sidebar-content js-simplebar" data-simplebar="init">
        <div class="simplebar-wrapper" style="margin: 0px;">
            <div class="simplebar-height-auto-observer-wrapper">
                <div class="simplebar-height-auto-observer"></div>
            </div>
            <div class="simplebar-mask">
                <div class="simplebar-offset" style="right: 0px; bottom: 0px;">
                    <div class="simplebar-content-wrapper" style="height: 100%; overflow: hidden scroll;">
                        <div class="simplebar-content">
                            <a class="sidebar-brand" href="{{ route('home') }}">
                                <x-application-logo
                                    class="logo-small p-0 m-0 align-middle d-inline-block"
                                    text="REET" />
                            </a>

                            <ul class="sidebar-nav">
                                <li class="sidebar-header">Σελίδες</li>

                                <!-- home -->
                                <li class="sidebar-item{{ activeLink('/') }}">
                                    <a class="sidebar-link" href="/">
                                        <i class="fas fa-home"></i>
                                        <span class="align-middle">Αρχική</span>
                                    </a>
                                </li>

                                <!-- users -->
                                @can('viewAny', App\Models\User::class)
                                <li class="sidebar-item{{ activeLink('users') }}">
                                    <a class="sidebar-link" href="{{ route('users.index') }}">
                                        <i class="fas fa-users"></i>
                                        <span class="align-middle">Χρήστες</span>
                                    </a>
                                </li>
                                @endcan

                                <!-- clubs -->
                                @can('viewAny', App\Models\Club::class)
                                <li class="sidebar-item{{ activeLink('clubs') }}">
                                    <a class="sidebar-link" href="{{ route('clubs.index') }}">
                                        <i class="fas fa-building"></i>
                                        <span class="align-middle">Σωματεία</span>
                                    </a>
                                </li>
                                @endcan

                                <!-- contacts -->
                                @can('viewAny', App\Models\Person::class)
                                <li class="sidebar-item{{ activeLink('people') }}">
                                    <a class="sidebar-link" href="{{ route('people.index') }}">
                                        <i class="fas fa-id-card"></i>
                                        <span class="align-middle">Επαφές</span>
                                    </a>
                                </li>
                                @endcan

                                <!-- abilities -->
                                @can('viewAny', App\Models\Ability::class)
                                <li class="sidebar-item{{ activeLink('abilities') }}">
                                    <a class="sidebar-link" href="{{ route('abilities.index') }}">
                                        <i class="fas fa-list-ul"></i>
                                        <span class="align-middle">Ιδιότητες</span>
                                    </a>
                                </li>
                                @endcan
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="simplebar-placeholder" style="width: auto; height: 957px;"></div>
        </div>
        <div class="simplebar-track simplebar-horizontal" style="visibility: hidden;">
            <div class="simplebar-scrollbar" style="width: 0px; display: none;"></div>
        </div>
        <div class="simplebar-track simplebar-vertical" style="visibility: visible;">
            <div class="simplebar-scrollbar" style="height: 509px; display: block; transform: translate3d(0px, 0px, 0px);"></div>
        </div>
    </div>
</nav>

resources/views/layouts/toolbar.blade.php
@isset($toolbar)
    <!-- Toolbar -->
    <div class="main-toolbar d-print-none">
        <div>
            {{ $toolbar }}
        </div>

    </div>
@endisset